### ISSUE TITLE
Change function has issues with large data sets for group by variables

### ISSUE THREAD

**Issue by AnneCU** [christophergandrud/DataCombine#10]
Hi Christopher,

I tried to calculate the change of absolute values of variable price within each group of day and securityid. Change function in DataCombine library runs really fast and the returning function was great when I tested with a small data set with only first 5000 variables. It returns NA at first row of each group and the change of prices within each group, but the change is not in absolute value but just the change value. When I tried to put it into my entire data set with more than 1m records, the first few thousands are doing pretty the same thing with the smaller dataset. However, after some point it cannot  figure out the first rows of each group. So I get the rest of the data all just with the price changes from last records and the groupvar doesn't contribute any more.

Here's my function used in R:
abs_change <- change(tradeinfo, Var = 'price', GroupVar = c('securityid','date'), slideBy = -1, type = "absolute").

It's really appreciated for your package since it's really fast and convenient. Looking forward to some further NEWS.

Thanks,
Anne

**Comment by christophergandrud** [comment]
My first guess would be that if your time variable is `date` then use the `TimeVar` argument:

```{r}
abs_change <- change(tradeinfo, Var = 'price', GroupVar = 'securityid', 
                                     TimeVar = 'date',
                                     slideBy = -1, type = "absolute")
```

Just let me know if the issue persists.

**Comment by AnneCU** [comment]
It's still not working well if I change the date to TimeVar.

**Comment by christophergandrud** [comment]
Is there any way to provide a reproducible example?

**Comment by AnneCU** [comment]
The data set is information sensitive, and was not permited to share. But I could try to produce some similar fake data later. The attributes for variables are securityid: numeric(7 digits eg: 3091176), date: numeric (8 digits eg: 20150112), Price numeric (float eg:200.63). The security would have several prices everyday(sometimes no price, sometimes only one price).

**Comment by AnneCU** [comment]
Hi Christopher, 

Sorry for the delay. Here's a simulated sample for the data I were using. FYI.

Thanks,
Anne

**Comment by AnneCU** [comment]
[rand data for test functions.zip](https://github.com/christophergandrud/DataCombine/files/184646/rand.data.for.test.functions.zip)

**Comment by christophergandrud** [comment]
Thanks. I'll try to find time to look into this over the next week or so.

**Comment by AnneCU** [comment]
Thanks so much! :)

**Comment by christophergandrud** [comment]
Hi @AnneCU 

I had a look at the data you sent and I don't seem to be able to reproduce the issue. Here is the code I used and the results I got:



```r
library(DataCombine)
library(rio)

tradeinfo <- import('rand data for test functions.csv')

abs_change <- change(tradeinfo, Var = 'Price', GroupVar = 'SecurityId', 
                     TimeVar = 'Date',
                     slideBy = -1, type = "absolute")
```

```
## 
## Lagging Price by 1 time units.
```

```r
# Find number of unique groups
length(unique(abs_change$SecurityId))
```

```
## [1] 3722
```

```r
# Find number of NAs
summary(abs_change$`Price_PChangeFrom-1`)
```

```
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
##  -100.1   -29.3     0.0     0.0    29.4   100.1    3722
```

You can see that the number of unique `SecurityId`'s is equal to the number of `NA`s in the change variable. I also visually checked and it looks like the changes are correct at the breaks between `SecurityId`'s.

**Comment by AnneCU** [comment]
Hi Christopher,

Thanks for the checking. This result is a little bit different than what I intended to create: I was intended to create a file which has break for each change of either securityid or date not just for change of securityid. 

When I used the code exactly as you used on my data it breaks when security id changes. But to make the breaks at each change of either securityid or date I changed the code to:

test<-  change(testing, Var = 'Price', GroupVar = c('SecurityId','Date'), slideBy = -1, type = "absolute")

and attached are the new testing files I were using which is closer to the real data. And please refer the the Testing results as what I obtained from the code.

Thanks,
[Testing results.zip](https://github.com/christophergandrud/DataCombine/files/192366/Testing.results.zip)


Anne

**Comment by AnneCU** [comment]
[Testing Files.zip](https://github.com/christophergandrud/DataCombine/files/192369/Testing.Files.zip)

**Comment by christophergandrud** [comment]
I'm having trouble unzipping this file.

Also please use:

```{r}
abs_change <- change(tradeinfo, Var = 'Price', GroupVar = 'SecurityId', 
                     TimeVar = 'Date',
                     slideBy = -1, type = "absolute")
```

**not**

```{r}
test<- change(testing, Var = 'Price', GroupVar = c('SecurityId','Date'), 
                       slideBy = -1, type = "absolute")
```

`Date` is the `TimeVar` not a `GroupVar`.

**Comment by AnneCU** [comment]
But what if I would like to have breaks for each security id each day? It seems that using the function you posted would just give breaks at each security but won't break for the change of date. The file is kind of too large to attach here and I split it when zipping but the other supporting files are not uploadable here. Would you like to provide an email address that I could send the files to?

Thanks,
Anne

**Comment by christophergandrud** [comment]
Sorry, I'm unsure what you mean by "breaks for each security id each day" could you give a simple example of what you would like the data to look like?

**Comment by AnneCU** [comment]
[Sample results.xlsx](https://github.com/christophergandrud/DataCombine/files/195807/Sample.results.xlsx)

**Comment by AnneCU** [comment]
Try this one...
[Sample results.xlsx](https://github.com/christophergandrud/DataCombine/files/195810/Sample.results.xlsx)

**Comment by christophergandrud** [comment]
Ah, now I understand better. Sorry about the confusion before. 

You basically want to treat the ID-Date as the group and find the change across the day, so what you need is a time indicator **within each Date** (e.g. hour-minute or something) to be the `TimeVar`. This will then ensure that the data is ordered correctly before finding the changes (any irregularity in the ordering will throw `change` off.

**Comment by AnneCU** [comment]
I see! I shall try with the time stamp to see how it goes. Thanks so much!

**Comment by christophergandrud** [comment]
Sure, no problem. And just let me know if there are any issues.

**Comment by AnneCU** [comment]
When the records reach up to about 5m, it still cannot break correctly at each group...

**Comment by christophergandrud** [comment]
Hm, there is either an issue with the grouping variables or some bug with `dplyr` which is ultimately doing the work behind the scenes. Have you tried to combine the securityId and Date variables into one variable?

**Comment by AnneCU** [comment]
Not yet... But I tried to group them using goup_by and calculate directly from the data itself and added a variable called order to get the beginning line of each group. Then get the desired result:
Test_O <- test%>% group_by(securityId,Date) %>% mutate(order = row_number())# get the squence number of each trade within group
Test_lag <- cbind(Test_O, lag = lag(Test_O$Price)) # Add column lag
Test_dif <-  cbind(Test_lag, dif = Test_lag$Price - Test_lag$lag ) 
Test_dif[which(Test_dif$order=1),] <- NA

**Comment by AnneCU** [comment]
I combined the securityId and Date variables into one variable and the breaks are good for this time!

**Comment by christophergandrud** [comment]
Great. There must be a wonky one somewhere deep down in the data set that throws off the following ordering.
