### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by mfjoseph** [christophergandrud/DataCombine#6]
Hi, 

When I try to install datacombine, I get a warning that reshape2 won't install correctly. 

I tried downloading and manually installing reshape2 then doing the same for dataCombine. I still can't get it to load. 

This is what i do and get
nstall.packages("C:/Users/mfjoseph/Desktop/DataCombine_0.2.7.1.tar.gz", repos = NULL, type = "source")
* installing *source* package 'DataCombine' ...
** package 'DataCombine' successfully unpacked and MD5 sums checked
** R
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'reshape2'
ERROR: lazy loading failed for package 'DataCombine'
* removing 'C:/Users/mfjoseph/Documents/R/R-3.1.1/library/DataCombine'
* restoring previous 'C:/Users/mfjoseph/Documents/R/R-3.1.1/library/DataCombine'
Warning in install.packages :
  running command '"C:/Users/mfjoseph/DOCUME~1/R/R-31~1.1/bin/i386/R" CMD INSTALL -l "C:\Users\mfjoseph\Documents\R\R-3.1.1\library" "C:/Users/mfjoseph/Desktop/DataCombine_0.2.7.1.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘C:/Users/mfjoseph/Desktop/DataCombine_0.2.7.1.tar.gz’ had non-zero exit status
> library(DataCombine)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘reshape2’
In addition: Warning message:
package ‘DataCombine’ was built under R version 3.1.2 
Error: package or namespace load failed for ‘DataCombine’

**Comment by christophergandrud** [comment]
Were you able to install reshape2?
