### ISSUE TITLE
data.table issues

### ISSUE THREAD

**Issue by zeltak** [christophergandrud/DataCombine#7]
Hi!

First of all thanks so much for this fantastic package! its a lifesaver for me :)

i have one question. i cant seem to get it to work with data.table at all.  this is the syntax i try to run:

#sort PM data
setkey(m9x,aodid,day)
# next day PM
Data1 <- slide(m9x, Var = "aod", GroupVar = "aodid",
               slideBy = 1)
#prev day PM 
Data2 <- slide(Data1, Var = "aod", GroupVar = "aodid",
               slideBy = -1)

this wont run but if i convert it to DF from DT and run it it works very well. any ideas?

thx again!

z.

**Comment by christophergandrud** [comment]
`slide` officially only works with data frames and there might be some conflict between `data.table`s and the `dplyr` functions that `slide` relies on.

What error messages do you get?

**Comment by zeltak** [comment]
Hi again

This is the error i get:

Error in data[, c(GroupVar, Var)] (from <text>#1) : incorrect number of dimensions

thx again!

z

**Comment by christophergandrud** [comment]
Yeah, I think the simplest thing is just to convert the data table to a data frame (e.g. `class(mx9) <- data.frame`) then run `slide`. 

`slide` outputs a data frame regardless. 

I've added a more informative error message regarding this issue to the dev build (399d8a67379cafc707b4ec9875026c6f39015a77).

**Comment by zeltak** [comment]
Thanks, i will just convert to DF as you suggested

best regards

Z
