### ISSUE TITLE
Bug in function "dMerge", argument "suffixes"

### ISSUE THREAD

**Issue by hplieninger** [christophergandrud/DataCombine#9]
I believe there is a bug in the `dMerge` function: The argument `suffixes` is overwritten in line 214 with
`suffixes = c(".x",".y"),`, which should be replaced by `suffixes = suffixes,` IMHO. Anyway, thanks for the package.

**Comment by christophergandrud** [comment]
Thanks for spotting! I've sorted it in bb5c6aa9bd8c1e750986160ddb61ad09fd3c82c2.
